"""
Export API — package generated code into a downloadable ZIP
with Dockerfile, requirements, and run instructions.
"""

from __future__ import annotations

import io
import logging
import zipfile
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from app.auth.auth import get_current_user
from app.db import get_conn

log = logging.getLogger(__name__)
router = APIRouter(prefix="/api/v1/export")


@router.get("/{task_id}")
async def export_task(
    task_id: str,
    user: dict = Depends(get_current_user),
):
    """Download generated code as a ZIP with Dockerfile + instructions."""
    conn = get_conn()
    task = conn.execute(
        "SELECT * FROM generation_tasks WHERE id = ? AND user_id = ?",
        (task_id, user["id"]),
    ).fetchone()

    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    if not task["generated_code"]:
        raise HTTPException(status_code=400, detail="No code generated for this task")

    code = task["generated_code"]
    lang = task["language"]
    idea = task["idea_text"][:60].replace(" ", "_").replace("/", "_")

    # Build file map
    files: dict[str, str] = {}

    if lang == "python":
        files["main.py"] = code
        files["requirements.txt"] = "# Add your dependencies here\n# flask\n# requests\n"
        files["Dockerfile"] = """FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py .
CMD ["python", "main.py"]
"""
        files["docker-compose.yml"] = """version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
"""
        files["README.md"] = f"""# {task["idea_text"][:60]}

Generated by Truffle AI.

## Run locally
```bash
python main.py
```

## Run with Docker
```bash
docker-compose up
```
"""

    elif lang == "javascript" or lang == "js":
        files["index.js"] = code
        files["package.json"] = """{
  "name": "nexus-export",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  }
}
"""
        files["Dockerfile"] = """FROM node:20-slim
WORKDIR /app
COPY package.json .
RUN npm install
COPY index.js .
CMD ["node", "index.js"]
"""
        files["README.md"] = f"""# {task["idea_text"][:60]}

## Run locally
```bash
node index.js
```

## Run with Docker
```bash
docker-compose up
```
"""

    elif lang == "go":
        files["main.go"] = code
        files["go.mod"] = "module nexus-export\n\ngo 1.21\n"
        files["Dockerfile"] = """FROM golang:1.21-alpine AS build
WORKDIR /app
COPY go.mod main.go .
RUN go build -o app .
FROM alpine
WORKDIR /app
COPY --from=build /app/app .
CMD ["./app"]
"""
        files["README.md"] = f"""# {task["idea_text"][:60]}

## Run locally
```bash
go run main.go
```

## Run with Docker
```bash
docker-compose up
```
"""

    elif lang == "cpp":
        files["main.cpp"] = code
        files["CMakeLists.txt"] = f"""cmake_minimum_required(VERSION 3.10)
project(nexus-export)
add_executable(app main.cpp)
"""
        files["Dockerfile"] = """FROM gcc:13-bookworm AS build
WORKDIR /app
COPY CMakeLists.txt main.cpp .
RUN mkdir build && cd build && cmake .. && make
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=build /app/build/app .
CMD ["./app"]
"""
        files["README.md"] = f"""# {task["idea_text"][:60]}

## Build & Run locally
```bash
cmake -B build && cmake --build build && ./build/app
```

## Run with Docker
```bash
docker-compose up
```
"""

    # Always add generic files
    if "docker-compose.yml" not in files:
        files["docker-compose.yml"] = """version: "3.8"
services:
  app:
    build: .
    restart: unless-stopped
"""

    # Build ZIP
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for path, content in files.items():
            zf.writestr(path, content)
    buf.seek(0)

    safe_name = idea.lower().replace(" ", "_")[:30] or "project"
    filename = f"{safe_name}.zip"

    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
